### ISSUE TITLE
Writing in nodefile

### ISSUE THREAD

**Issue by ftherrien** [pylada/pylada-light#24]
https://github.com/pylada/pylada-light/blob/7e78d8f16304b932f792befa513443caef0ecf35/config/mpi.py#L75-L76

It seems like this line should be writing elsewhere. In the previous commit it was writing directly in the standard output. Should it be writing in the logger now? Writing this in the nodefile itself makes the %launch function fail.

**Comment by ftherrien** [comment]
I suggest:
`print "config/mpi: machine_dep_call_mod: nodefile contents: \"%s\"" % fin.read()`
to be consistant with the previous behavior, or:
`logger.debug("config/mpi: machine_dep_call_mod: nodefile contents: \"%s\"" % fin.read())`
I can commit the changes, I just don't know which one is preferable.

**Comment by mdavezac** [comment]
Thanks! It would have been more kosher to do this via a pull request though :)
I think the error on travis is unrelated. Probably something about them using too old a version of ubuntu...

**Comment by ftherrien** [comment]
Yes you are right sorry! I did not realize I can do a pull-request even if I can pull directly. I will know for next time!
I am not sure what the problem is with travis. What is the error output?

**Comment by mdavezac** [comment]
No worries. To do a PR in the same repo, you just need to make changes in a separate branch.
I'll take care of the Travis error (see #27). It's just an infrastructure issue.
Thanks again!
