### ISSUE TITLE
Installation fails when mpi4py is unavailable

### ISSUE THREAD

**Issue by samtsevich** [pylada/pylada-light#39]
Hello!

I have ptyhon3.7 and tried to compile pylada on my Mac.
I ran `python3 setup.py install` and it gives me finally an error:

`error: package directory 'build/pylada/process/tests' does not exist`

Then I tried to compile it by hands and made and everything is fine until I am importing pylada inside python3 it says follows:

```
>>> import pylada
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pylada'

```

Then I checked _site-packages_ folder and I did not find pylada directory there.

What can be wrong with it?

**Comment by mdavezac** [comment]
I'm not quite sure. I've just tried on a mac with python3.7 and did not encounter any issues.

Could try from a clean repo (`git clean -xdf` will remove everything but file from the repo, including ignored files), pull from source, and then post the full `python setup.py install` output?

Also, when compiling by hand, you do have to build `make` and then install `make install`. Or you can run from the build directory with `./locapython.sh -m IPython`.

**Comment by mdavezac** [comment]
I'm not sure what you mean by *wrong* `PYTHON_PKG_DIR`. When calling `python setup.py install` the goal is to install pylada in the most likely package location, as given by setuptools. It happens [here](https://github.com/pylada/pylada-light/blob/7bdb1ce5f28f887a41ef76c960c7f23c6dec77c4/setup.py#L110) in pylada's setup.py. It does install correctly in a virtualenv. And it should install to home if running `python setup.py install --user`, though I have not tried that.

When running things manually via cmake, you can specify with `cmake -DPYTHON_PKG_DIR=/installation/path/for/python packages /path/to/build/directory".

**Comment by mdavezac** [comment]
The error seems to happen whem mpi4py cannot be found. mpi4py should be optional. I'll try and figure out what the problem is. Meanwhile, you may want to try and install mpi4py.

**Comment by ftherrien** [comment]
I just encountered the same error. @mdavezac, you are right, it's because of mpi4py. In process/tests/CmakeLists.txt line 23:

`if(tests AND mpi4py_FOUND)`

If mpi4py is not found then "process/tests" is not copied to "build" and "pkg_install". Removing "AND mpi4py_FOUND" solves the issue but it is not a clean solution...

In setup.py we could do something along the lines of:

```
try:
    import mpi4py
    packages = ['pylada', ... , 'pylada.process', 'pylada.process.tests', 'pylada.vasp', ... ]
except ImportError:
    packages = ['pylada', ... , 'pylada.process', 'pylada.vasp', ... ]

setup( ....
    packages = packages,
    ...)
```

**Comment by mdavezac** [comment]
Actually, I was thinking we should have something like that in the tests, to disable them if mpi4py is not found. That way, cmake does not need to know about mpi4py. It would be all handled on the python side.

Pytest has the [right functionality](https://docs.pytest.org/en/latest/skipping.html#id1) for this as well.

**Comment by samtsevich** [comment]
> The error seems to happen whem mpi4py cannot be found. mpi4py should be optional. I'll try and figure out what the problem is. Meanwhile, you may want to try and install mpi4py.

Thanks!
Now it compiled properly and works fine.
