### ISSUE TITLE
gmake (cmake) error.

### ISSUE THREAD

**Issue by Woohyuny** [pylada/pylada-light#43]
Hello. I faced the problem of gmake error. My local have two cmake version (cmake, cmake3). So I modify setup.py as cmake = find_executable('cmake3').  The cmake3 's version is 3.12.1 and then I did 'python setup.py install'. Below is the error. 

[ 54%] Built target pylada.crystal
[ 57%] Building CXX object crystal/defects/CMakeFiles/third_order.dir/third_order.cc.o
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc: In function ‘pylada::types::t_real pylada::third_order(const Eigen::MatrixBase<Derived>&, pylada::types::t_int)’:
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc:43:26: error: ‘v’ does not name a type
               auto const v = rVector3d(i * ninv + l - 0.5, j * ninv + m - 0.5, k * ninv + n - 0.5);
                          ^
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc:44:43: error: ‘v’ was not declared in this scope
               t_real const q = (_matrix * v).squaredNorm();
                                           ^
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc: In function ‘pylada::types::t_real pylada::third_order(const t_real*, pylada::types::t_int)’:
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc:56:14: error: ‘matrix’ does not name a type
   auto const matrix = types::rMatrix3d::Map(_matrix).transpose();
              ^
/home/woohyun/9_program/pylada_light_python2/pylada-light-master/crystal/defects/third_order.cc:57:22: error: ‘matrix’ was not declared in this scope
   return third_order(matrix, _n);
                      ^
gmake[2]: *** [crystal/defects/CMakeFiles/third_order.dir/third_order.cc.o] error 1
gmake[1]: *** [crystal/defects/CMakeFiles/third_order.dir/all] error 2
gmake: *** [all] error 2
error: command '/usr/bin/cmake3' failed with exit status 2

**Comment by mdavezac** [comment]
It looks like c+11 is not detected, could you try running deleting the build directory and running:

```bash
CXXFLAGS=-std=c++11 python setup.py install
```

**Comment by Woohyuny** [comment]
Thanks!! :) I solved the problem

**Comment by vstevano** [comment]
Hi Mayeul, let me chime in on this.

I had the same problem on a machine that forces me to use conda and intel compilers. Did what you suggested and the installation finished smoothly. However when trying to import pylada this happened:

(myenv) ipython
Python 3.6.5 |Anaconda custom (64-bit)| (default, Oct 12 2018, 19:28:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pylada
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c57a77c5694a> in <module>()
----> 1 import pylada

~/.conda/envs/myenv/lib/python3.6/site-packages/pylada/__init__.py in <module>()
    129 
    130 # import submodules
--> 131 from . import error, crystal, physics, misc, tools, ewald, decorations, periodic_table, vasp, \
    132     process, jobfolder, logger, espresso
    133 

ImportError: /u/us/hi/vstevano/.conda/envs/myenv/lib/python3.6/site-packages/pylada/ewald.so: undefined symbol: for_write_seq_fmt_xmit

Do you have any idea what is going on?

Thanks,
Vladan

**Comment by mdavezac** [comment]
That's probably because the linker that was used was not ifort (ewald is the one bit of fortran that's in there). I don't know of a straightforward way of correcting this.
