### ISSUE TITLE
Error in third_order.cc

### ISSUE THREAD

**Issue by xabimen** [pylada/pylada-light#48]
I got the following error while installing pylada:
    
[ 57%] Building CXX object crystal/defects/CMakeFiles/third_order.dir/third_order.cc.o
    /tmp/pip-req-build-bs7_xdv1/crystal/defects/third_order.cc: In function ‘pylada::types::t_real pylada::third_order(const Eigen::MatrixBase<Derived>&, pylada::types::t_int)’:
    /tmp/pip-req-build-bs7_xdv1/crystal/defects/third_order.cc:43:26: error: ‘v’ does not name a type
                   auto const v = rVector3d(i * ninv + l - 0.5, j * ninv + m - 0.5, k * ninv + n - 0.5);

**Comment by mdavezac** [comment]
This looks like the same problem as #43. Could you try [this solution](https://github.com/pylada/pylada-light/issues/43#issuecomment-436906709)?

**Comment by xabimen** [comment]
Thansk, the installation worked fine. Now I have a problem when importing some modules:

import pylada.crystal.read as pcread
  File "/home/xabier/.local/lib/python3.5/site-packages/pylada/__init__.py", line 131, in <module>
    from . import error, crystal, physics, misc, tools, ewald, decorations, periodic_table, vasp, \
  File "/home/xabier/.local/lib/python3.5/site-packages/pylada/crystal/__init__.py", line 32, in <module>
    from ._space_group import space_group, cell_invariants
ImportError: dynamic module does not define module export function (PyInit__space_group)

**Comment by mdavezac** [comment]
That looks suspiciously like the code was compiled for python2, and then run on python3.
How did you go about trying to install pylada? The simplest would be to do either download the code and run `python setup.py install` or do `pip3 install git+https://github.com/pylada/pylada-light`.

**Comment by tolatolatop** [comment]
I have another problem with third_order.cc while installing pylada.

[ 57%] Building CXX object crystal/defects/CMakeFiles/third_order.dir/third_order.cc.o

/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc: In function ‘pylada::types::t_real pylada::third_order(const Eigen::MatrixBase<Derived>&, pylada::types::t_int)’:
/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc:43:26: error: ‘v’ does not name a type
&nbsp;&nbsp;&nbsp;&nbsp;auto const v = rVector3d(i * ninv + l - 0.5, j * ninv + m - 0.5, k * ninv + n - 0.5);
/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc:44:43: error: ‘v’ was not declared in this scope
&nbsp;&nbsp;&nbsp;&nbsp;t_real const q = (_matrix * v).squaredNorm();
/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc: In function ‘pylada::types::t_real &nbsp;&nbsp;&nbsp;&nbsp;pylada::third_order(const t_real*, pylada::types::t_int)’:
/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc:56:14: error: ‘matrix’ does not name a type
   auto const matrix = types::rMatrix3d::Map(_matrix).transpose();
/tmp/pip-req-build-1o4dta2v/crystal/defects/third_order.cc:57:22: error: ‘matrix’ was not declared in this scope
&nbsp;&nbsp;&nbsp;&nbsp;return third_order(matrix, _n);
gmake[2]: *** [crystal/defects/CMakeFiles/third_order.dir/third_order.cc.o] Error 1
gmake[1]: *** [crystal/defects/CMakeFiles/third_order.dir/all] Error 2
gmake: *** [all] Error 2
error: command '/usr/local/bin/cmake' failed with exit status 2

**Comment by mdavezac** [comment]
This is a linux file permission problem. Maybe you tried to install pylada with "sudo" at some point? Unless you are installing system-wide, sudo should not be necessary.
You can check permissions and who owns the file with "ls -lh /home/xbChen/software/anaconda3/lib/python3.6/site-packages/pylada/" and possible change ownership with "sudo chown -R xbChen /home/xbChen/software/anaconda3/lib/python3.6/site-packages/pylada/".

**Comment by tolatolatop** [comment]
It's work! Thanks. I remove some files built by root.
