### ISSUE TITLE
Pmpaths

### ISSUE THREAD

**Issue by XJtsinghua1992** [pylada/pylada-light#64]
Hi expert,

It seems I have installed pylada in Python 3.9.8. But I cannot use "from pathfinder.pmpaths import main".

![image](https://user-images.githubusercontent.com/122658010/212448467-52daa452-08bf-4f52-bb5e-adff12fbb6a9.png)

Thank you very much
Jian

**Comment by ftherrien** [comment]
Pmpath is not included with pylada, take a look at [p2ptrans](https://github.com/ftherrien/p2ptrans) or contact Vladan Stevanovic for the latest version of pmpath.

**Comment by XJtsinghua1992** [comment]
Thank you !

**Comment by XJtsinghua1992** [comment]
Hi expert,

I tried to install p2ptrans in Python 3.9.8. 
But an error occurs:
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf .

I tried to change the version of numpy to 1.19, 1.20, 1.21, and 1.22, but does not work.

May I kindly ask how to solve it? Thank you.

Best,
Jian

**Comment by XJtsinghua1992** [comment]
I upgrade the numpy to 1.23 version, and now I can intall p2ptrans successfully.
